import "bootstrap/dist/css/bootstrap.css";
import 'antd/dist/antd.css';
import "../styles/globals.css";
import Head from "next/head";
import SideNav from "../components/Navbar/navbar";


function MyApp({ Component, pageProps }) {

  return <div>
    <Head>
      <title>Tat App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    </Head>
    <SideNav />
    <Component {...pageProps} />
  </div>;
}

export default MyApp;
